apiVersion: v1
kind: Service
metadata:
  name: backend-headless
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  clusterIP: None
  ports:
    - name: api
      port: 80
