apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "common.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: ui
      protocol: TCP
      port: 80
      targetPort: 80
